[build]
command = "npm run netlify:build"
publish = "public"
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"
external_node_modules = ["ejs"]
included_files = ["src/views/**", "public/**"]

[[redirects]]
from = "/*"
to = "/.netlify/functions/render"
status = 200